# Site settings
title: Brad + Jekyll
email: arizona.flahive@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Getting to know Jekyll a little more, what a great tool.
  Cool to work with and easy to use.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  bradflahive

# Build settings
markdown: kramdown
